apiVersion: 1

datasources:
  - name: OpenWebUI SQLite
    type: frser-sqlite-datasource
    uid: openwebui-sqlite
    access: proxy
    jsonData:
      path: /var/lib/grafana/openwebui.db
    editable: false
