server {
    listen 80;
    server_name search.dolkens.net search.dolkens.au;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name search.dolkens.net search.dolkens.au;

    ssl_certificate     /etc/letsencrypt/live/search.dolkens.net/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/search.dolkens.net/privkey.pem;
    ssl_protocols       TLSv1.2 TLSv1.3;
    ssl_ciphers         HIGH:!aNULL:!MD5;

    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;

    resolver 127.0.0.11 valid=10s;
    set $upstream http://searxng:8080;

    location / {
        proxy_pass $upstream;
    }
}
