auth:
  enabled: true

go2rtc:
  streams:
    house-cam:
      - rtsp://{FRIGATE_NVR_HOSTNAME}:7447/{FRIGATE_NVR_TOKEN_HOUSE_CAM_HIGH}
      - rtsp://{FRIGATE_NVR_HOSTNAME}:7447/{FRIGATE_NVR_TOKEN_HOUSE_CAM_MEDIUM}
    fruit-patrol:
      - rtsp://{FRIGATE_NVR_HOSTNAME}:7447/{FRIGATE_NVR_TOKEN_FRUIT_PATROL_HIGH}
      - rtsp://{FRIGATE_NVR_HOSTNAME}:7447/{FRIGATE_NVR_TOKEN_FRUIT_PATROL_MEDIUM}
    drive-cam:
      - rtsp://{FRIGATE_NVR_HOSTNAME}:7447/{FRIGATE_NVR_TOKEN_DRIVE_CAM_HIGH}
      - rtsp://{FRIGATE_NVR_HOSTNAME}:7447/{FRIGATE_NVR_TOKEN_DRIVE_CAM_MEDIUM}
    bird-cam:
      - rtsp://{FRIGATE_NVR_HOSTNAME}:7447/{FRIGATE_NVR_TOKEN_BIRD_CAM_HIGH}
      - rtsp://{FRIGATE_NVR_HOSTNAME}:7447/{FRIGATE_NVR_TOKEN_BIRD_CAM_MEDIUM}
    door-cam:
      - rtsp://{FRIGATE_NVR_HOSTNAME}:7447/{FRIGATE_NVR_TOKEN_DOOR_CAM_HIGH}
      - rtsp://{FRIGATE_NVR_HOSTNAME}:7447/{FRIGATE_NVR_TOKEN_DOOR_CAM_MEDIUM}
    creek-cam:
      - rtsp://{FRIGATE_NVR_HOSTNAME}:7447/{FRIGATE_NVR_TOKEN_CREEK_CAM_HIGH}
      - rtsp://{FRIGATE_NVR_HOSTNAME}:7447/{FRIGATE_NVR_TOKEN_CREEK_CAM_MEDIUM}
    willie-patrol:
      - rtsp://{FRIGATE_NVR_HOSTNAME}:7447/{FRIGATE_NVR_TOKEN_WILLIE_PATROL_HIGH}
      - rtsp://{FRIGATE_NVR_HOSTNAME}:7447/{FRIGATE_NVR_TOKEN_WILLIE_PATROL_MEDIUM}
    shed-cam:
      - rtsp://{FRIGATE_NVR_HOSTNAME}:7447/{FRIGATE_NVR_TOKEN_SHED_CAM_HIGH}
      - rtsp://{FRIGATE_NVR_HOSTNAME}:7447/{FRIGATE_NVR_TOKEN_SHED_CAM_MEDIUM}
    bench-cam:
      - rtsp://{FRIGATE_NVR_HOSTNAME}:7447/{FRIGATE_NVR_TOKEN_BENCH_CAM_HIGH}
      - rtsp://{FRIGATE_NVR_HOSTNAME}:7447/{FRIGATE_NVR_TOKEN_BENCH_CAM_MEDIUM}
    office-cam:
      - rtsp://{FRIGATE_NVR_HOSTNAME}:7447/{FRIGATE_NVR_TOKEN_OFFICE_CAM_HIGH}
      - rtsp://{FRIGATE_NVR_HOSTNAME}:7447/{FRIGATE_NVR_TOKEN_OFFICE_CAM_MEDIUM}

mqtt:
  enabled: true
  host: '{FRIGATE_MQTT_HOSTNAME}'
  user: '{FRIGATE_MQTT_USERNAME}'
  password: '{FRIGATE_MQTT_PASSWORD}'

database:
  path: /media/frigate/frigate.db

detectors:
  onnx:
    type: onnx

model:
  model_type: rfdetr
  width: 320
  height: 320
  input_tensor: nchw
  input_pixel_format: rgb
  input_dtype: float
  path: /config/model_cache/rfdetr-Nano.onnx

detect:
  enabled: true

ffmpeg:
  global_args: -hide_banner
    -loglevel warning
    -threads 2
  hwaccel_args: preset-nvidia
  output_args:
    record: -f segment
      -segment_time 10
      -segment_format mp4
      -reset_timestamps 1 
      -strftime 1 -c copy


record:
  enabled: true
  alerts:
    pre_capture: 10
    post_capture: 10
    retain:
      days: 31
  detections:
    pre_capture: 10
    post_capture: 10
    retain:
      days: 7
  continuous:
    days: 1
  motion:
    days: 1
  preview:
    quality: very_high
snapshots:
  enabled: true
  retain:
    default: 14

cameras:
  house-cam:
    ffmpeg:
      inputs:
        - path: rtsp://{FRIGATE_NVR_HOSTNAME}:7447/{FRIGATE_NVR_TOKEN_HOUSE_CAM_HIGH}
          roles: [record]
        - path: rtsp://{FRIGATE_NVR_HOSTNAME}:7447/{FRIGATE_NVR_TOKEN_HOUSE_CAM_MEDIUM}
          roles: [detect]
    detect:
      width: 1280
      height: 720
      fps: 5
    motion:
      threshold: 60
      contour_area: 50
      mask:
        - 0,0,420,0,420,30,0,30
    objects:
      track:
        - person
        - bird
        - car
        - bus
        - motorcycle
        - cat
        - dog
      filters:
        person:
          min_score: 0.75
          min_area: 1500

  fruit-patrol:
    ffmpeg:
      inputs:
        - path: rtsp://{FRIGATE_NVR_HOSTNAME}:7447/{FRIGATE_NVR_TOKEN_FRUIT_PATROL_HIGH}
          roles: [record]
        - path: rtsp://{FRIGATE_NVR_HOSTNAME}:7447/{FRIGATE_NVR_TOKEN_FRUIT_PATROL_MEDIUM}
          roles: [detect]
    detect:
      width: 1280
      height: 720
      fps: 3
    motion:
      threshold: 65
      mask:
        - 0,0,420,0,420,30,0,30
    objects:
      track:
        - person
        - bird
        - car
        - bus
        - motorcycle
        - cat
        - dog

  drive-cam:
    ffmpeg:
      inputs:
        - path: rtsp://{FRIGATE_NVR_HOSTNAME}:7447/{FRIGATE_NVR_TOKEN_DRIVE_CAM_HIGH}
          roles: [record]
        - path: rtsp://{FRIGATE_NVR_HOSTNAME}:7447/{FRIGATE_NVR_TOKEN_DRIVE_CAM_MEDIUM}
          roles: [detect]
    detect:
      width: 1024
      height: 576
      fps: 3
    motion:
      threshold: 50
      mask:
        - 0,0,360,0,360,29,0,29
    objects:
      track:
        - person
        - bird
        - car
        - bus
        - motorcycle
        - cat
        - dog

  bird-cam:
    ffmpeg:
      inputs:
        - path: rtsp://{FRIGATE_NVR_HOSTNAME}:7447/{FRIGATE_NVR_TOKEN_BIRD_CAM_HIGH}
          roles: [record]
        - path: rtsp://{FRIGATE_NVR_HOSTNAME}:7447/{FRIGATE_NVR_TOKEN_BIRD_CAM_MEDIUM}
          roles: [detect]
    detect:
      width: 1280
      height: 720
      fps: 3
    motion:
      threshold: 55
      improve_contrast: true
      mask:
        - 0,0,420,0,420,30,0,30
#        - 0,0,1280,0,1280,50,0,50
    objects:
      track:
        - person
        - bird
        - car
        - bus
        - motorcycle
        - cat
        - dog
      filters:
        bird:
          min_score: 0.65
          min_area: 500
        person:
          min_score: 0.75
          min_area: 1500

  door-cam:
    ui:
      dashboard: false
    ffmpeg:
      inputs:
        - path: rtsp://{FRIGATE_NVR_HOSTNAME}:7447/{FRIGATE_NVR_TOKEN_DOOR_CAM_HIGH}
          roles: [record]
        - path: rtsp://{FRIGATE_NVR_HOSTNAME}:7447/{FRIGATE_NVR_TOKEN_DOOR_CAM_MEDIUM}
          roles: [detect]
    detect:
      width: 480
      height: 640
      fps: 5
    motion:
      threshold: 60
      mask:
        - 0,0,300,0,300,36,0,36
    objects:
      track:
        - person

  creek-cam:
    ffmpeg:
      inputs:
        - path: rtsp://{FRIGATE_NVR_HOSTNAME}:7447/{FRIGATE_NVR_TOKEN_CREEK_CAM_HIGH}
          roles: [record]
        - path: rtsp://{FRIGATE_NVR_HOSTNAME}:7447/{FRIGATE_NVR_TOKEN_CREEK_CAM_MEDIUM}
          roles: [detect]
    detect:
      width: 1280
      height: 720
      fps: 3
    motion:
      threshold: 75
      mask:
        - 0,0,420,0,420,30,0,30
    objects:
      track:
        - person
        - bird
        - car
        - bus
        - motorcycle
        - cat
        - dog

  willie-patrol:
    ffmpeg:
      inputs:
        - path: rtsp://{FRIGATE_NVR_HOSTNAME}:7447/{FRIGATE_NVR_TOKEN_WILLIE_PATROL_HIGH}
          roles: [record]
        - path: rtsp://{FRIGATE_NVR_HOSTNAME}:7447/{FRIGATE_NVR_TOKEN_WILLIE_PATROL_MEDIUM}
          roles: [detect]
    detect:
      width: 1280
      height: 720
      fps: 3
    motion:
      threshold: 65
      mask:
        - 0,0,420,0,420,30,0,30
    objects:
      track:
        - person
        - bird
        - car
        - bus
        - motorcycle
        - cat
        - dog

  shed-cam:
    ffmpeg:
      inputs:
        - path: rtsp://{FRIGATE_NVR_HOSTNAME}:7447/{FRIGATE_NVR_TOKEN_SHED_CAM_HIGH}
          roles: [record]
        - path: rtsp://{FRIGATE_NVR_HOSTNAME}:7447/{FRIGATE_NVR_TOKEN_SHED_CAM_MEDIUM}
          roles: [detect]
    detect:
      width: 1024
      height: 576
      fps: 1
    motion:
      threshold: 60
      mask:
        - 0,0,360,0,360,29,0,29
    objects:
      track:
        - person

  bench-cam:
    ffmpeg:
      inputs:
        - path: rtsp://{FRIGATE_NVR_HOSTNAME}:7447/{FRIGATE_NVR_TOKEN_BENCH_CAM_HIGH}
          roles: [record]
        - path: rtsp://{FRIGATE_NVR_HOSTNAME}:7447/{FRIGATE_NVR_TOKEN_BENCH_CAM_MEDIUM}
          roles: [detect]
    detect:
      width: 1024
      height: 576
      fps: 1
    motion:
      threshold: 65
      mask:
        - 0,0,360,0,360,29,0,29
    objects:
      track:
        - person

  office-cam:
    ui:
      dashboard: false
    ffmpeg:
      inputs:
        - path: rtsp://{FRIGATE_NVR_HOSTNAME}:7447/{FRIGATE_NVR_TOKEN_OFFICE_CAM_HIGH}
          roles: [record]
        - path: rtsp://{FRIGATE_NVR_HOSTNAME}:7447/{FRIGATE_NVR_TOKEN_OFFICE_CAM_MEDIUM}
          roles: [detect]
    detect:
      enabled: false
      width: 1280
      height: 720
      fps: 3
    motion:
      mask:
        - 0,0,420,0,420,30,0,30
    objects:
      track:
        - person

version: 0.17-0